# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NuBits
email: ryan@skycatchfire.com
description: "World's Best Stable Digital Currencies"
url: "https://www.nubits.com" # with the https protocol
baseurl: "" # the subpath of your site, e.g. /blog
enforce_ssl: "www.nubits.com" # without any protocol

# Build settings
markdown: kramdown

sass:
  style: compressed

include: ["_pages"]

menu-list: ["About", "Exchanges", "Liquidity Pools", "Resources", "Connect", "NuShares", "Download"]
