# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NuBits
email: team@nubits.com
description: "World's Best Stable Digital Currencies"
url: "https://nubits.com" # with the https protocol
baseurl: "" # the subpath of your site, e.g. /blog
enforce_ssl: "nubits.com" # without any protocol

# Build settings
markdown: kramdown

sass:
  style: compressed

include:
  - "_pages"
  - ".well-known" # Matrix federation for NuBits Chat, https://github.com/matrix-org/synapse/blob/master/docs/federate.md

plugins:
  - jekyll-redirect-from
